# Generated by Django 4.1 on 2022-08-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='who_updated',
        ),
    ]
