version: '3'

services:
  cache:
    image: redis:alpine
    restart: always
    env_file: .env
    expose:
      - 6379

  db:
    image: postgres:14-alpine
    restart: always
    env_file: .env
    expose:
      - 5432

  backend: &backend
    build: ./
    restart: always
    command: >
      bash -c "python manage.py migrate --noinput
      && python manage.py collectstatic --clear --noinput
      && gunicorn --access-logfile - --workers 4 --timeout 600 --reload --bind backend:8000 webcap_shop.wsgi:application"
    env_file: .env
    ports:
      - 127.0.0.1:9595:8000
    volumes:
      - .:/code

    depends_on:
      - db
      - cache
    links:
      - db:db
      - cache:redis

  celery:
    <<: *backend
    command: bash -c "celery -A webcap_shop worker -l INFO -B"
    restart: always
    env_file: .env
    ports: []
    depends_on:
      - backend
