### Login StoreMaster
POST http://localhost:8000/user/auth/login
Content-Type: application/json

{
  "email": "b@b.cc",
  "password": "password123"
}

> {%
  client.global.set("access_token", response.body.access);
  client.global.set("refresh_token", response.body.refresh);
%}


### Get List of Order with Bill
#Success, Status: 200
#{
#  "success": true,
#  "status_code": 200,
#  "message": "Successfully fetched products",
#  "products": [
#    {
#      "id": 18,
#      "order_key": "20220902130102-10",
#      "total_paid": "1.12",
#      "created_by": 9,
#      "status": 1,
#      "bill": {
#        "order": 18,
#        "product": "product #4",
#        "price": "1.12",
#        "quantity": 1,
#        "is_discount": false,
#        "discount_price": 0.0,
#        "created": "2022-09-02T13:43:02.661514Z"
#      }
#    }
#  ]
#}
GET http://localhost:8000/store/order/list/
Authorization: JWT {{access_token}}
Content-Type: application/json

### Get List of Orders with int date
GET http://localhost:8000/store/order/list/20220901/20220930/
Authorization: JWT {{access_token}}
Content-Type: application/json


### Get List of Orders with str date
GET http://localhost:8000/store/order/list/01.07.2022/01.09.2022/
Authorization: JWT {{access_token}}
Content-Type: application/json


### Order Update Status
POST http://localhost:8000/store/order/update/
Authorization: JWT {{access_token}}
Content-Type: application/json

{
  "order_id": 3
}

### Order Close
POST http://localhost:8000/store/order/close/
Authorization: JWT {{access_token}}
Content-Type: application/json

{
  "order_id": 2
}

### Order By Id
GET http://localhost:8000/store/order/get/2
Authorization: JWT {{access_token}}
Content-Type: application/json

### Order By Id
GET http://localhost:9595/store/order/get/20
Authorization: JWT {{access_token}}
Content-Type: application/json
